obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.25 #0.18
inflation_radius: 0.6 #0.55

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#map_update_rate = 
footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.3, 0.0], [0.25, -0.25]]
transform_tolerance: 1.0 #0.2
